name: Build & Deploy UI (Qt WebAssembly)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_ui:
    runs-on: ubuntu-24.04
    outputs:
      pages_path: ${{ steps.setout.outputs.path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Emscripten (emsdk 3.1.70)
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.70
      - name: Print emsdk info
        run: |
          echo "EMSDK=$EMSDK"
          echo "EMSCRIPTEN=$EMSCRIPTEN"
          which emcc && emcc -v

      - name: Install Qt 6.9.2 (wasm)
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.2
          host: all_os
          target: wasm
          arch: wasm_singlethread
          cache: true

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y ninja-build python3

      - name: Build UI via script
        env:
          QT_ROOT: ${{ runner.workspace }}/Qt
          QT_CHAINLOAD_TOOLCHAIN_FILE: ${{ env.EMSCRIPTEN }}/cmake/Modules/Platform/Emscripten.cmake
          CMAKE_GENERATOR: Ninja
          CMAKE_MAKE_PROGRAM: /usr/bin/ninja
          REVO_CI: "1"
        run: |
          cd ui
          echo "QT_ROOT=$QT_ROOT"
          echo "QT_CHAINLOAD_TOOLCHAIN_FILE=${QT_CHAINLOAD_TOOLCHAIN_FILE}"
          echo "EMSDK=${EMSDK}"
          echo "EMSCRIPTEN=${EMSCRIPTEN}"
          echo "QT_ROOT_DIR=${QT_ROOT_DIR:-<unset>}  (from action)"
          echo "QT_HOST_PATH=${QT_HOST_PATH:-<unset>} (from action)"
          which qt-cmake || true
          qt-cmake --version || true

          chmod +x build-ui.sh
          ./build-ui.sh

      - name: Set output path for pages
        id: setout
        run: echo "path=ui/build-ui" >> $GITHUB_OUTPUT

      - name: Upload artifact (full wasm build)
        uses: actions/upload-artifact@v4
        with:
          name: ui-${{ github.sha }}
          path: ui/build-ui
          if-no-files-found: error

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ui/build-ui

  deploy:
    needs: build_ui
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4